build:
	g++ -std=c++17 -Wall -Wextra walsh.cpp -o walsh
	g++ -std=c++17 -Wall -Wextra statistics.cpp -o statistics
	g++ -std=c++17 -Wall -Wextra prinel.cpp -o prinel
	g++ -std=c++17 -Wall -Wextra crypto.cpp -o crypto

run-p1:
	./walsh

run-p2:
	./statistics

run-p3:
	./prinel

run-p4:
	./crypto

clean:
	rm -f walsh
	rm -f statistics
	rm -f prinel
	rm -f crypto

.PHONY: clean
